### ISSUE TITLE
README.md to add the each of the template's screenshot

### ISSUE THREAD

**Issue by edgars** [nasph-io/sharkdoc-docussaurus-base#1]
Goal: To add the screenshots of each of the available site templates inside the project.

**Comment by CrystianP-Company** [comment]
Resolved commit  [preview](https://github.com/nasph-io/sharkdoc-site-templates/commit/80e9d185ac59ad801551d9d676d8e759c07cc042)

- Template AttoBot [preview](https://github.com/nasph-io/sharkdoc-site-templates/blob/main/attobot/PREVIEW.md)
- Template Benthos [preview](https://github.com/nasph-io/sharkdoc-site-templates/blob/main/benthos/PREVIEW.md)
- Template Csc-website [preview](https://github.com/nasph-io/sharkdoc-site-templates/blob/main/csc-website/PREVIEW.md)
- Template Default [preview](https://github.com/nasph-io/sharkdoc-site-templates/blob/main/default/PREVIEW.md)
